import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const pg = new PGlite();
await pg.exec(`create schema auth; create table auth.users(id uuid primary key); create role anon; create role authenticated; create role service_role bypassrls;`);
const sql=fs.readFileSync(new URL('../migrations/012_andrea.sql', import.meta.url),'utf8');
await pg.exec(sql);await pg.exec(sql); // repeatable migration
const uid='11111111-1111-4111-8111-111111111111', other='22222222-2222-4222-8222-222222222222';
await pg.query('insert into auth.users values ($1),($2)',[uid,other]);
const call=async(fn,args)=> (await pg.query(`select public.${fn}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as result`,args)).rows[0].result;
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
let checks=0;
const eq=(a,b)=>{assert.deepEqual(a,b);checks++;};
eq((await call('andrea_state',[uid,false])).free_ratings_remaining,3);
eq((await call('andrea_state',[uid,true])).welcome_seen,true);
const reserve=(rid,pro=false,lease=id(900))=>call('andrea_reserve_rating',[uid,rid,'photo',pro,lease]);
const finish=(rid,status='completed',lease=id(900))=>call('andrea_finish_rating',[uid,rid,lease,status,JSON.stringify({score:8})]);
eq((await reserve(id(1))).status,'reserved');
eq((await reserve(id(2))).status,'busy');
eq((await reserve(id(1))).status,'processing');
eq(await finish(id(1),'completed',id(999)),false);
eq(await finish(id(1)),true);
eq(await finish(id(1)),false);
eq((await reserve(id(1))).status,'completed');
eq((await call('andrea_reserve_rating',[uid,id(1),'different',false,id(900)])).status,'conflict');
eq((await reserve(id(2))).status,'reserved');eq(await finish(id(2),'retake'),true);
eq((await call('andrea_state',[uid,false])).free_ratings_remaining,2);
eq((await reserve(id(3))).status,'reserved');eq(await finish(id(3),'failed'),true);
eq((await reserve(id(3))).status,'reserved');eq(await finish(id(3)),true);
eq((await reserve(id(4))).status,'reserved');eq(await finish(id(4)),true);
eq((await reserve(id(5))).status,'pro_required');
eq((await reserve(id(5),true)).status,'reserved');eq(await finish(id(5)),true);
eq((await call('andrea_state',[uid,false])).free_ratings_remaining,0);
eq(await call('andrea_get_rating',[other,id(1)]),null);
for(let i=0;i<3;i++) eq(await call('andrea_claim_budget',['chat','global',3,86400]),true);
eq(await call('andrea_claim_budget',['chat','global',3,86400]),false);
// Expired lease is reclaimable, but its old worker cannot commit a result.
eq((await reserve(id(6),true,id(901))).status,'reserved');
await pg.exec(`update andrea_rating_requests set lease_until=now()-interval '1 second' where request_id='${id(6)}'`);
eq((await reserve(id(6),true,id(902))).status,'reserved');
eq(await finish(id(6),'completed',id(901)),false);eq(await finish(id(6),'completed',id(902)),true);
await call('andrea_clear_recovery',[uid]);eq((await call('andrea_get_rating',[uid,id(1)])).status,'expired');
eq((await call('andrea_state',[uid,false])).free_ratings_remaining,0);
// Public clients cannot reserve credits or read another user's metadata.
await pg.exec('set role authenticated');
let denied=false;try{await call('andrea_reserve_rating',[uid,id(20),'x',true,id(900)]);}catch{denied=true;}eq(denied,true);
await pg.exec('reset role');await pg.query('delete from auth.users where id=$1',[uid]);
eq((await pg.query('select count(*)::integer as n from andrea_rating_requests where user_id=$1',[uid])).rows[0].n,0);
console.log(`${checks} SQL assertions passed; migration reapplied successfully.`);
await pg.close();
